name       : python-eventlet
version    : 0.33.0
release    : 2
source     :
    - https://pypi.io/packages/source/e/eventlet/eventlet-0.33.0.tar.gz : 80144f489c1bb273a51b6f96ff9785a382d2866b9bab1f5bd748385019f4141f
license    : MIT
component  : programming.python
summary    : Highly concurrent networking library
description: |
    Eventlet is a concurrent networking library for Python that allows you to change how you run your code, not how you write it.
builddeps  :
    - dnspython
    - python-greenlet
    - python-nose
    - python-openssl
rundeps    :
    - dnspython
    - python-greenlet
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    nosetests
